### ISSUE TITLE
Error gravisimo!!!!

### ISSUE THREAD

**Issue by Javierfernandezrubio** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-DavidFontalba#3]
Miralo por dios que me duelen los ojos!

@DavidFontalba 
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-DavidFontalba/blob/67548cb66de8332b1979960a9d1fa0cffd5cfd12/Fraccion.py#L90

**Comment by DavidFontalba** [comment]
:(
